spring.application.name=backEnd
server.port=8386
lark.app-id=cli_a8563adbd3b95010
lark.app-secret=cE1L6Q1GgLF1ZZlovVJmvgY7P7GXSeeR
lark.redirect-uri=http://localhost:8386/oauth/callback
# lark.redirect-uri=http://100.70.133.122:8386/oauth/callback
report.cache.dir=./data/report-cache
report.cache.ttl-seconds=3600
pos.base-url=https://pos.pages.fm/api/v1/shops/1546758
pos.api-key=2a6ed8b51a8d4ae49a851d5876b00018

server.servlet.session.timeout=8h

# Logging configuration
logging.level.org.report.backend.webhook=DEBUG
logging.level.org.springframework.web=DEBUG